/*
Copyright 2021 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "k8s.io/cloud-provider-vsphere/pkg/cloudprovider/vsphereparavirtual/apis/nsxnetworking/v1alpha1"
)

// FakeStaticRoutes implements StaticRouteInterface
type FakeStaticRoutes struct {
	Fake *FakeNsxV1alpha1
	ns   string
}

var staticroutesResource = schema.GroupVersionResource{Group: "nsx.vmware.com", Version: "v1alpha1", Resource: "staticroutes"}

var staticroutesKind = schema.GroupVersionKind{Group: "nsx.vmware.com", Version: "v1alpha1", Kind: "StaticRoute"}

// Get takes name of the staticRoute, and returns the corresponding staticRoute object, and an error if there is any.
func (c *FakeStaticRoutes) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.StaticRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(staticroutesResource, c.ns, name), &v1alpha1.StaticRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StaticRoute), err
}

// List takes label and field selectors, and returns the list of StaticRoutes that match those selectors.
func (c *FakeStaticRoutes) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.StaticRouteList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(staticroutesResource, staticroutesKind, c.ns, opts), &v1alpha1.StaticRouteList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.StaticRouteList{ListMeta: obj.(*v1alpha1.StaticRouteList).ListMeta}
	for _, item := range obj.(*v1alpha1.StaticRouteList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested staticRoutes.
func (c *FakeStaticRoutes) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(staticroutesResource, c.ns, opts))

}

// Create takes the representation of a staticRoute and creates it.  Returns the server's representation of the staticRoute, and an error, if there is any.
func (c *FakeStaticRoutes) Create(ctx context.Context, staticRoute *v1alpha1.StaticRoute, opts v1.CreateOptions) (result *v1alpha1.StaticRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(staticroutesResource, c.ns, staticRoute), &v1alpha1.StaticRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StaticRoute), err
}

// Update takes the representation of a staticRoute and updates it. Returns the server's representation of the staticRoute, and an error, if there is any.
func (c *FakeStaticRoutes) Update(ctx context.Context, staticRoute *v1alpha1.StaticRoute, opts v1.UpdateOptions) (result *v1alpha1.StaticRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(staticroutesResource, c.ns, staticRoute), &v1alpha1.StaticRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StaticRoute), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeStaticRoutes) UpdateStatus(ctx context.Context, staticRoute *v1alpha1.StaticRoute, opts v1.UpdateOptions) (*v1alpha1.StaticRoute, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(staticroutesResource, "status", c.ns, staticRoute), &v1alpha1.StaticRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StaticRoute), err
}

// Delete takes name of the staticRoute and deletes it. Returns an error if one occurs.
func (c *FakeStaticRoutes) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(staticroutesResource, c.ns, name, opts), &v1alpha1.StaticRoute{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeStaticRoutes) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(staticroutesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.StaticRouteList{})
	return err
}

// Patch applies the patch and returns the patched staticRoute.
func (c *FakeStaticRoutes) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.StaticRoute, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(staticroutesResource, c.ns, name, pt, data, subresources...), &v1alpha1.StaticRoute{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StaticRoute), err
}
